sudo: false
language: node_js
cache:
  directories:
    - node_modules
    - jspm_packages
notifications:
  email: false
node_js:
  - '6'
before_install:
  - npm install -g cypress-cli
before_script:
  - npm prune
  - gulp build
script:
  - npm run lint
  - cypress ci --config fileServerFolder=`pwd`,baseUrl=dist/index.html#
